# Generated by Django 5.0.4 on 2024-08-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('ben_id', models.AutoField(primary_key=True, serialize=False)),
                ('ben_name', models.CharField(max_length=255)),
                ('ben_phno', models.CharField(max_length=255)),
                ('ben_email', models.CharField(max_length=255)),
                ('ben_pref', models.CharField(max_length=255)),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('org_type', models.CharField(max_length=255)),
                ('org_phno', models.CharField(max_length=255)),
                ('org_email', models.CharField(max_length=255)),
                ('org_loc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('supply_type', models.CharField(max_length=255)),
                ('supply_category', models.CharField(max_length=255)),
                ('supply_quantity', models.CharField(max_length=255)),
                ('supply_unit', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('supply_descr', models.CharField(max_length=255)),
                ('supply_condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('is_read', models.BooleanField()),
                ('ben', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.benefactor')),
            ],
        ),
        migrations.AddField(
            model_name='benefactor',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.organisation'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_req', models.CharField(max_length=255)),
                ('req_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('dest_loc', models.CharField(max_length=255)),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.benefactor')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.supply')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_donated', models.CharField(max_length=255)),
                ('donation_date', models.DateField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.benefactor')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.supply')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyShipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_shipped', models.CharField(max_length=255)),
                ('shipment_date', models.DateField()),
                ('expected_delivery', models.DateField()),
                ('actual_delivery', models.DateField()),
                ('delivery_status', models.CharField(max_length=255)),
                ('tracking_no', models.IntegerField()),
                ('delivery_comments', models.CharField(max_length=255)),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.request')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.supply')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyTrans',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_type', models.CharField(max_length=255)),
                ('trans_quantity', models.CharField(max_length=255)),
                ('trans_date', models.DateField()),
                ('trans_comments', models.CharField(max_length=255)),
                ('ben', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.benefactor')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.supply')),
            ],
        ),
    ]
