# Generated by Django 5.0.4 on 2024-08-08 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='ben_email',
            field=models.CharField(db_column='ben_email', max_length=255),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='ben_id',
            field=models.AutoField(db_column='ben_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='ben_name',
            field=models.CharField(db_column='ben_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='ben_phno',
            field=models.CharField(db_column='ben_phno', max_length=255),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='ben_pref',
            field=models.CharField(db_column='ben_pref', max_length=255),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='org',
            field=models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, to='care.organisation'),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(db_column='donation_date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_id',
            field=models.AutoField(db_column='donation_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(db_column='donor_id', on_delete=django.db.models.deletion.CASCADE, to='care.benefactor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity_donated',
            field=models.CharField(db_column='quantity_donated', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='supply',
            field=models.ForeignKey(db_column='supply_id', on_delete=django.db.models.deletion.CASCADE, to='care.supply'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ben',
            field=models.ForeignKey(db_column='ben_id', on_delete=django.db.models.deletion.CASCADE, to='care.benefactor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_column='is_read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(db_column='message', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_id',
            field=models.AutoField(db_column='notif_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(db_column='notif_type', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_email',
            field=models.CharField(db_column='org_email', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_id',
            field=models.AutoField(db_column='org_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_loc',
            field=models.CharField(db_column='org_loc', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_name',
            field=models.CharField(db_column='org_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_phno',
            field=models.CharField(db_column='org_phno', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_type',
            field=models.CharField(db_column='org_type', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='comments',
            field=models.CharField(db_column='comments', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='dest_loc',
            field=models.CharField(db_column='dest_loc', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(db_column='priority', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity_req',
            field=models.CharField(db_column='quantity_req', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.CharField(db_column='reason', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='rec',
            field=models.ForeignKey(db_column='rec_id', on_delete=django.db.models.deletion.CASCADE, to='care.benefactor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_date',
            field=models.DateField(db_column='req_date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_id',
            field=models.AutoField(db_column='req_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(db_column='status', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='supply',
            field=models.ForeignKey(db_column='supply_id', on_delete=django.db.models.deletion.CASCADE, to='care.supply'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='expiration_date',
            field=models.DateField(db_column='expiration_date'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_category',
            field=models.CharField(db_column='supply_category', max_length=255),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_condition',
            field=models.CharField(db_column='supply_condition', max_length=255),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_descr',
            field=models.CharField(db_column='supply_descr', max_length=255),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_id',
            field=models.AutoField(db_column='supply_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_quantity',
            field=models.CharField(db_column='supply_quantity', max_length=255),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_type',
            field=models.CharField(db_column='supply_type', max_length=255),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_unit',
            field=models.CharField(db_column='supply_unit', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='actual_delivery',
            field=models.DateField(db_column='actual_delivery'),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='delivery_comments',
            field=models.CharField(db_column='delivery_comments', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='delivery_status',
            field=models.CharField(db_column='delivery_status', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='expected_delivery',
            field=models.DateField(db_column='expected_delivery'),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='quantity_shipped',
            field=models.CharField(db_column='quantity_shipped', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='req',
            field=models.ForeignKey(db_column='req_id', on_delete=django.db.models.deletion.CASCADE, to='care.request'),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='shipment_date',
            field=models.DateField(db_column='shipment_date'),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='shipment_id',
            field=models.AutoField(db_column='shipment_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='supply',
            field=models.ForeignKey(db_column='supply_id', on_delete=django.db.models.deletion.CASCADE, to='care.supply'),
        ),
        migrations.AlterField(
            model_name='supplyshipment',
            name='tracking_no',
            field=models.IntegerField(db_column='tracking_no'),
        ),
        migrations.AlterField(
            model_name='supplytrans',
            name='ben',
            field=models.ForeignKey(db_column='ben_id', on_delete=django.db.models.deletion.CASCADE, to='care.benefactor'),
        ),
        migrations.AlterField(
            model_name='supplytrans',
            name='supply',
            field=models.ForeignKey(db_column='supply_id', on_delete=django.db.models.deletion.CASCADE, to='care.supply'),
        ),
        migrations.AlterField(
            model_name='supplytrans',
            name='trans_comments',
            field=models.CharField(db_column='trans_comments', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplytrans',
            name='trans_date',
            field=models.DateField(db_column='trans_date'),
        ),
        migrations.AlterField(
            model_name='supplytrans',
            name='trans_id',
            field=models.AutoField(db_column='trans_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplytrans',
            name='trans_quantity',
            field=models.CharField(db_column='trans_quantity', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplytrans',
            name='trans_type',
            field=models.CharField(db_column='trans_type', max_length=255),
        ),
        migrations.AlterModelTable(
            name='benefactor',
            table='benefactor',
        ),
        migrations.AlterModelTable(
            name='donation',
            table='donation',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='organisation',
            table='organisation',
        ),
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
        migrations.AlterModelTable(
            name='supply',
            table='supply',
        ),
        migrations.AlterModelTable(
            name='supplyshipment',
            table='supply_shipment',
        ),
        migrations.AlterModelTable(
            name='supplytrans',
            table='supply_trans',
        ),
    ]
